apiVersion: v1
kind: Service
metadata:
  name: parchment-discord
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: www.patreon.com
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP